/**
 * TextNote Model
 * Represents a diary/journal entry created manually by the user
 *
 * Platform: Cross-platform (Web + Mobile)
 * Storage: Firestore (textNotes collection)
 * Local: WatermelonDB (text_notes table) on mobile, localStorage on web
 * Embedding: Generated by Cloud Function after creation
 */

export interface TextNote {
  id?: string;
  userId: string;
  title: string;
  content: string;
  tags: string[];
  location?: {
    latitude: number;
    longitude: number;
    address: string | null;
    locationId: string | null; // Reference to locationData record if correlated
  };
  createdAt: string; // ISO string
  updatedAt: string; // ISO string
  embeddingId: string | null; // Pinecone vector ID (text_{noteId})
  embeddingCreatedAt?: string; // ISO string
  embeddingError?: string; // Error message if embedding generation failed
}

/**
 * TextNote Draft (for auto-save in UI)
 */
export interface TextNoteDraft {
  title: string;
  content: string;
  tags: string[];
  location?: {
    latitude: number;
    longitude: number;
    address: string | null;
  };
  lastSaved: string; // ISO string
}

/**
 * TextNote Validation Result
 */
export interface TextNoteValidationResult {
  isValid: boolean;
  errors: string[];
}
